name: Selenium Tests CI for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    env:
      GITHUB_ACTIONS: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        # Скачиваем Chrome напрямую
        $chromeUrl = "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe"
        $chromeInstaller = "ChromeStandaloneSetup64.exe"
        Invoke-WebRequest -Uri $chromeUrl -OutFile $chromeInstaller
        Start-Process -FilePath $chromeInstaller -Args "/silent /install" -Wait
        Remove-Item $chromeInstaller

    - name: Start HTTP server
      run: |
        python -m http.server 8000 &
        Start-Sleep -Seconds 10

    - name: Run Selenium Tests
      run: pytest tests/ -v --tb=short
